language: node_js

cache:
  directories:
    - backend/node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

before_install:
  - cd backend/

install:
  - npm install

script:
  - yarn test

script:
  - npm run tsc --noImplicitAny false
  
notifications:
  email:
    reciepients:
      - martiniroqueesteban@gmail.com
    on_success: always
    on_failure: always

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  local_dir: dist/
  api_key: $HEROKU_API_KEY # desde heroku
  app: backend-node-design-patterns  
  on:
    repo: SuichiM/node-design-patterns
