version: "3"
services:
  backend:
    build:
      context: backend
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 8888:8888
    environment:
      - COMMAND=${BACKEND_COMMAND}
  frontend:
    build:
        context: frontend
    volumes:
        - ./frontend:/home/node/app
        - /home/node/app/node_modules
    ports:
        - 8889:80
    environment:
        - COMMAND=${FRONTEND_COMMAND}
        - BACKEND_URL=${BACKEND_URL}