version: '3'
services:
    web:
        build: .
        volumes:
            - .:/home/node/app
            - /home/node/app/node_modules
        expose:
            - 8888
            - 8889
        ports:
            - 8888:8888
            - 8889:8889
